[phases.setup]
nixPkgs = ["nodejs", "php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan route:clear && php artisan migrate --force && php artisan user:create-admin admin@slpa.lk Admin123 || true"
